"use client";

import { FormEvent, useState } from "react";
import Icon from "@/components/ui/Icon";

export default function FormPengaduan() {
  const [terkirim, setTerkirim] = useState(false); const [lampiran, setLampiran] = useState("");
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setTerkirim(true); }
  if (terkirim) return <div className="rounded-xl border border-primary-container bg-surface p-8 text-center shadow-level1"><Icon name="task_alt" filled size={56} className="text-primary" /><h2 className="mt-4 text-2xl font-bold text-primary">Pengaduan berhasil dikirim</h2><p className="mx-auto mt-2 max-w-lg text-on-surface-variant">Terima kasih atas laporan Anda. Petugas Nagari akan meninjau dan menindaklanjuti pengaduan ini.</p><button onClick={() => setTerkirim(false)} className="mt-6 min-h-11 rounded-lg border border-primary px-5 text-sm font-semibold text-primary hover:bg-primary hover:text-on-primary">Kirim pengaduan lain</button></div>;
  const input = "mt-1 min-h-11 w-full rounded-md border border-outline-variant bg-surface-container-low px-3 py-2 text-sm text-on-surface placeholder:text-outline";
  return <form onSubmit={submit} className="relative overflow-hidden rounded-xl border border-outline-variant bg-surface p-5 shadow-level1 md:p-8"><div className="pointer-events-none absolute right-0 top-0 h-28 w-28 rounded-bl-full bg-secondary-container/30" /><h2 className="mb-6 text-2xl font-bold text-primary">Formulir Pengaduan</h2><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-on-surface">Nomor Induk Kependudukan (NIK) *<input required inputMode="numeric" pattern="[0-9]{16}" title="Masukkan 16 digit NIK" className={input} placeholder="Masukkan 16 digit NIK" /></label><label className="text-sm font-semibold text-on-surface">Nama Lengkap *<input required className={input} placeholder="Sesuai KTP" /></label><label className="text-sm font-semibold text-on-surface">Nomor Handphone (WhatsApp) *<input required type="tel" className={input} placeholder="Contoh: 08123456789" /></label><label className="text-sm font-semibold text-on-surface">Kategori Laporan *<select required defaultValue="" className={input}><option value="" disabled>Pilih kategori</option><option>Infrastruktur & Lingkungan</option><option>Layanan Administrasi</option><option>Kesejahteraan Sosial</option><option>Ketertiban & Keamanan</option><option>Lainnya</option></select></label></div><label className="mt-4 block text-sm font-semibold text-on-surface">Judul Laporan *<input required className={input} placeholder="Singkat dan jelas" /></label><label className="mt-4 block text-sm font-semibold text-on-surface">Detail Laporan *<textarea required rows={5} className={input} placeholder="Ceritakan kronologi atau detail permasalahan secara lengkap…" /></label><div className="mt-4"><p className="text-sm font-semibold text-on-surface">Lampiran bukti (opsional, maks. 5 MB)</p><label className="mt-1 flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-md border-2 border-dashed border-outline-variant bg-surface-container-lowest p-4 text-center hover:bg-surface-container-low"><Icon name="cloud_upload" size={34} className="text-outline" /><span className="mt-2 text-sm font-semibold text-primary">{lampiran || "Unggah foto atau PDF"}</span><input type="file" accept="image/*,.pdf" className="sr-only" onChange={(e) => setLampiran(e.target.files?.[0]?.name || "")} /></label></div><label className="mt-4 flex items-start gap-3 text-sm text-on-surface-variant"><input type="checkbox" className="mt-1 size-4 accent-primary" /><span>Kirim sebagai anonim <span className="text-outline">(identitas Anda tidak akan dipublikasikan)</span></span></label><button className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-md bg-primary px-6 py-3 text-sm font-bold text-on-primary transition hover:bg-primary-container"><Icon name="send" size={18} />Kirim Pengaduan</button><p className="mt-3 text-xs text-on-surface-variant">Data pada formulir ini hanya digunakan untuk menindaklanjuti laporan Anda.</p></form>;
}
